database:
  host:
  name:
  user:
  port:
  password:
messages:
  collected: "&aYou have been collected %amount%!"
  giveCommand:
    invalidAmount: "&cError, invalid amount! (Must be a number)"
    success: "&bYou had given %amount% to %player%!"
  helpCommand:
    - "&7-------------------------"
    - "&6Bank Note Help"
    - "&7&l>> &b/terrabank give <player> <amount> &7: give bank note to player"
    - "&7&l>> &b/terrabank reload &7: reload configuration (not recommanded, prefer a server restart)" # Its recommanded to fully restart the server
    - "&7&l>> &b/terrabank withdraw &7: the bank's withdraw menu"
    - "&7&l>> &b/terrabank help &7: show this help page"
    - "&7-------------------------"

bankNote:
  keyword: "&7Billet"
  currencySymbol: "€"
  item: PAPER
  display-name: "%keyword% %value%%currencySymbol%"
  description:
    - "§6Clique droit pour encaisser"
    - "&e&lATTENTION &cVous allez encaisser tout le paquet de billet !"
    - "&cSéparez les si vous ne voulez pas tout encaisser."


withdraw:
  messages:
    enterAmount:
      - "&eVeuillez entrer un montant "
      - "&eou tapez &e&l0 &epour annuler !"
    enterNumber:
      - "&eCombien de billet(s) de &7%enteredAmount%€ &esouhaitez-vous ? &c&l(Nombre entier)"
      - "&eOu tapez &e&l0 &epour annuler !"
    invalidAmount: "&cTransaction annulée, montant invalide. "
    invalidNumber: "&cTransaction annulée, nombre invalide. "
    notEnoughMoney: "&cVous n'avez pas assez d'argent !"
    received: "&aVous avez reçu %number% billet(s) de %amount% !"
  menu:
    title: "           &e&l⚡ &bBANQUE &e&l⚡        "
    rows: 1
    items:
      decoration:
        event: $decoration
        material: "BLUE_STAINED_GLASS_PANE"
        name: ""
        slot:
          - 0
          - 1
          - 2
          - 3
          - 5
          - 6
          - 7
      close:
        event: $close
        material: "RED_STAINED_GLASS_PANE"
        name: "&cFermer le menu"
        slot:
          - 8
      withdraw:
        event: $withdraw
        material: "PAPER"
        slot:
          - 4
        name: "&b&l>> Retirer de l'argent"
        lore:
          - "&7Retire de l'argent pour notamment"
          - "&7acheter aux villageois du marché"
          - "&7ou échanger avec nimporte qui !"