# You have to connect TerraBank to the database of lightEconomy
database:
  host:
  name:
  user:
  port:
  password:
messages:
  giveCommand:
    invalidAmount: "&cError, invalid amount ! (Must be a number)"
    success: "&bYou had gived &7%amount% &bto &7%player% !"
  helpCommand:
    - "&7-------------------------"
    - "&6Bank Note Help"
    - "&7&l>> &b/terrabank give <player> <amount> &7: give bank note to player"
    - "&7&l>> &b/terrabank reload &7:reload configuration"
    - "&7&l>> &b/terrabank help &7:show this help page"
    - "&7-------------------------"
  collected: "§aYou have been collected %amount% !"
bankNote:
  item: PAPER
  display-name: "&6BankNote %value%"
  description:
    - "§6Click to collect money !"