# You have to connect TerraBank to the database of lightEconomy
database:
  host:
  name:
  user:
  port:
  password:
messages:
  giveCommand:
    invalidAmount: "&cError, invalid amount ! (Must be a number)"
    success: "&bYou had gived &7%amount% &bto &7%player% !"
bankNote:
  item: PAPER
  display-name: "&6BankNote %value%"
  description:
    - "ยง6Click to collect money !"