database:
  host:
  name:
  user:
  port:
  password:
messages:
  collected: "&aYou have been collected %amount%!"
  giveCommand:
    invalidAmount: "&cError, invalid amount! (Must be a number)"
    success: "&bYou had given %amount% to %player%!"
  helpCommand:
    - "&7-------------------------"
    - "&6Bank Note Help"
    - "&7&l>> &b/terrabank give <player> <amount> &7: give bank note to player"
    - "&7&l>> &b/terrabank reload &7: reload configuration"
    - "&7&l>> &b/terrabank help &7: show this help page"
    - "&7-------------------------"

bankNote:
  keyword: "&7Banknote"
  currencySymbol: "$"
  item: PAPER
  display-name: "%keyword% %currencySymbol%%value%"
  description:
    - "ยง6Click to collect money!"

